version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge 